version: '3.6'

services: 
    mysqldb:
        container_name: mysql-local
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: aeidb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports: 
            - "3306:3306"
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080

    aei-state-event-consumer-app:
        image: aei-state-event-consumer:0.0.1-SNAPSHOT
        container_name: aei-state-event-consumer-app
        hostname: aei-state-event-consumer-app
        restart: on-failure
        depends_on: 
            - mysqldb
        environment: 
            rds_host_name: mysql-local
            rds_port: 3306
            rds_db: aeidb
            rds_user: user
            rds_password: user
            server.port: 8200
        volumes: 
            - ./var/logs/aei-state-event-consumer-app
        ports:
        - "8200:8200"

    nginx-lb:
        image: library/nginx:latest
        container_name: nginx-lb
        hostname: nginx-lb
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
        - "80:80"
        depends_on:
        - aei-product-inventory-api-1
        - aei-product-inventory-api-2

    aei-product-inventory-api-1:
        image: aei-product-inventory-api:0.0.1-SNAPSHOT
        container_name: aei-product-inventory-api-1
        hostname: aei-product-inventory-api-1
        restart: on-failure
        depends_on: 
            - mysqldb
        environment: 
            rds_host_name: mysql-local
            rds_port: 3306
            rds_db: aeidb
            rds_user: user
            rds_password: user
            server.port: 8100
        volumes: 
            - ./var/logs/aei-product-inventory-api-1
        ports:
        - "8101:8100"

    aei-product-inventory-api-2:
        image: aei-product-inventory-api:0.0.1-SNAPSHOT
        container_name: aei-product-inventory-api-2
        hostname: aei-product-inventory-api-2
        restart: on-failure
        depends_on: 
            - mysqldb
        environment: 
            rds_host_name: mysql-local
            rds_port: 3306
            rds_db: aeidb
            rds_user: user
            rds_password: user
            server.port: 8100
        volumes: 
            - ./var/logs/aei-product-inventory-api-2
        ports:
        - "8102:8100"
